### PR TITLE
Performance Instrumentation

### LINKED ISSUE #39: Move Skylight Instrumentation
We should extract and move the Skylight instrumentation into the Skylight gem.

Skylight gem already provides a set of probes, including support for AMS:
https://github.com/skylightio/skylight-ruby/blob/master/skylight-core/lib/skylight/core/probes/active_model_serializers.rb

### PR DESCRIPTION
**Pull request by stas**
## What is the current behavior?

This is partially related to the #106 and should help identify the performance issues easier. Closes #39 

Currently the performance instrumentation is outdated and would automatically enable for all the serializers.

Also, the Skylight support is reported to not work and generally requires an update to work.

## What is the new behavior?

The instrumentation support was update to work per serializer.

The documentation has been updated as well.

The Skylight support was removed and will be submitted to be part of the `skylight` gem.

## Checklist

Please make sure the following requirements are complete:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes /
  features)
- [x] All automated checks pass (CI/CD)

### CODE REVIEW

**Comment by stas** [comment]
@GuiTeK do you think you can enable the instrumentation to validate some of the concerns raised in #106 

Maybe we can add instrumentation separately for the attributes and relationships serialization if that helps...

**Comment by ziggythehamster** [comment]
Can I suggest also instrumenting `get_included_records` and `relationships_hash`? It may be that primary data is rendered fairly quickly, but secondary data (inclusions, relationships) isn't, and it'd be helpful to know this. (Maybe you have a has_many with 10k items and just getting the ID for that takes a while.)

**Comment by GuiTeK** [comment]
@stas Thank you for working on this issue! Yes I could enable instrumentation in our testing environment. Without skylight, how do you suggest to save the metrics?

I tested today the changes made by @nbibler but I didn't really notice any improvements over large payloads (~11 MB JSON payload).

@ziggythehamster Yes, I think it would be interesting, indeed I have several `has_many` relationships.

**Comment by nbibler** [comment]
@GuiTeK : I'm not sure what your structure is for generating the JSON. This performance increase is specifically to improve the time for serializing JSON with deeply nested included objects.

For us, we're generating ~5MB to ~20MB of JSON and seeing orders of magnitude difference in processing time to generate it. But, we're also including (and **I wouldn't recommend doing this!**) a _**large**, deep_ list of objects in the serialization. The include list is well over 800 items long and over 10 levels deep. Again, not something I recommend doing and JSON:API isn't _really_ intended to be exercised in this way. It just so happened to highlight the performance issue of this library very clearly because the dataset is so extreme.

**Comment by stas** [comment]
> @stas Thank you for working on this issue! Yes I could enable instrumentation in our testing environment. Without skylight, how do you suggest to save the metrics?

Please refer to the AS Instrumentation to learn about all the notifications you can subscribe:
https://guides.rubyonrails.org/active_support_instrumentation.html

You can collect the notification stats from the moment when a request is received and track it down until it's rendered.



> I tested today the changes made by @nbibler but I didn't really notice any improvements over large payloads (~11 MB JSON payload).

@GuiTeK please try to keep the conversations related. There's already a thread related to #103 and the performance comparisons indeed reflect a significant improvement. If you have a different use-case, let's open a new issue and discuss it there.

@ziggythehamster I updated the support for related methods.

Thank you all for the feedback!

**Pull request merged**
